all: assets/acshm assets/acbridge.exe

CC=gcc
WINECC=x86_64-w64-mingw32-gcc
CFLAGS=-DASSETTOCORSA -Wall -Os -g

assets/acshm: createsimshm.c
	$(CC) $< $(CFLAGS) -o $@

assets/acbridge.exe: simshmbridge.c
	$(WINECC) $< $(CFLAGS) -mconsole -o $@

clean:
	rm -f assets/acshm assets/acbridge.exe

# vim: syntax=make ts=4 sw=4 sts=4 sr noet
